name: Build & Test
on:
  - push
  - pull_request

jobs:
  spin_up:
    runs-on: [self-hosted, master]
    steps:
    - name: Spin Up VM
      id: spin_up
      uses: jeff-vincent/orka-actions-spin-up@master
      with:
        orkaIP: http://10.221.188.100
        orkaUser: ${{ secrets.ORKA_USER }}
        orkaPass: ${{ secrets.ORKA_PASS }}
        orkaBaseImage: gh_actions_v5.img
        githubUser: ${{ secrets.GH_USER }}
        githubPat: ${{ secrets.GH_PAT }}
        githubRepoName: bintrail-swift-sdk
    outputs:
      uniqueVMActionsTag: ${{ steps.spin_up.outputs.uniqueVMActionsTag }}
      vmName: ${{ steps.spin_up.outputs.vmName }}
      orkaNodeName: ${{ steps.spin_up.outputs.orkaNodeName }}
  macOS:
    needs: spin_up
    name: Test macOS
    runs-on: [self-hosted, "${{ needs.spin_up.outputs.uniqueVMActionsTag }}"]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build and test
        run: ./ci test macOS
  iOS:
    needs: spin_up
    name: Test iOS
    runs-on: [self-hosted, "${{ needs.spin_up.outputs.uniqueVMActionsTag }}"]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build and test
        run: ./ci test iOS "iPhone"
  tvOS:
    needs: spin_up
    name: Test tvOS
    runs-on: [self-hosted, "${{ needs.spin_up.outputs.uniqueVMActionsTag }}"]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build and test
        run: ./ci test tvOS "Apple TV"
  watchOS:
    needs: spin_up
    name: Build watchOS
    runs-on: [self-hosted, "${{ needs.spin_up.outputs.uniqueVMActionsTag }}"]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build
        run: ./ci build watchOS "Apple Watch"

  spm-macOS:
    needs: [spin_up, macOS]
    name: Test Swift Package manager (macOS)
    runs-on: [self-hosted, "${{ needs.spin_up.outputs.uniqueVMActionsTag }}"]
    steps:
      - uses: actions/checkout@v1
      - name: swift test
        run: swift test
  tear_down:
    if: always()
    needs: [spin_up, macOS, tvOS, watchOS, spm-macOS]
    runs-on: [self-hosted, master]
    steps:
    - name: Tear Down VM
      id: tear_down
      uses: jeff-vincent/orka-actions-tear-down@master
      with:
        orkaUser: ${{ secrets.ORKA_USER }}
        orkaPass: ${{ secrets.ORKA_PASS }}
        vmName: ${{ needs.spin_up.outputs.vmName }}
        githubUser: ${{ secrets.GH_USER }}
        githubPat: ${{ secrets.GH_PAT }}
        githubRepoName: bintrail-swift-sdk

