name: Build & Test
on:
  - push
  - pull_request

jobs:
  spin_up:
    runs-on: [self-hosted, master]
    steps:
    - name: Spin Up VM
      id: spin_up
      uses: jeff-vincent/orka-actions-spin-up@master
      with:
        orkaIP: http://10.221.188.100
        orkaUser: ${{ secrets.ORKA_USER }}
        orkaPass: ${{ secrets.ORKA_PASS }}
        orkaBaseImage: gha_catalina_v2.img
        githubUser: ${{ secrets.GH_USER }}
        githubPat: ${{ secrets.GH_PAT }}
        githubRepoName: bintrail-swift-sdk
    outputs:
      uniqueVMActionsTag: ${{ steps.spin_up.outputs.uniqueVMActionsTag }}
      vmName: ${{ steps.spin_up.outputs.vmName }}
      orkaNodeName: ${{ steps.spin_up.outputs.orkaNodeName }}
  watchOS:
    needs: spin_up
    name: Build watchOS
    runs-on: [self-hosted, "${{ needs.spin_up.outputs.uniqueVMActionsTag }}"]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build
        run: ./ci build watchOS "Apple Watch"
  tear_down:
    if: always()
    needs: [spin_up, watchOS]
    runs-on: [self-hosted, master]
    steps:
    - name: Tear Down VM
      id: tear_down
      uses: jeff-vincent/orka-actions-tear-down@master
      with:
        orkaUser: ${{ secrets.ORKA_USER }}
        orkaPass: ${{ secrets.ORKA_PASS }}
        vmName: ${{ needs.spin_up.outputs.vmName }}
        githubUser: ${{ secrets.GH_USER }}
        githubPat: ${{ secrets.GH_PAT }}
        githubRepoName: bintrail-swift-sdk
